name: Github Actions trial  
on:
  push:
    branches:
    - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say hello to the user 
        run: echo "Hello From Github Actions"
      - name: asking about his health 
        run: echo "3amel eh ya hamam "
        
